services:
  nginx:
    volumes:
      - ./nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app-prod
  app-prod:
    container_name: app-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    env_file: .env.prod
    command: npm run start:prod
    networks:
      - jordan-net
